### ISSUE TITLE
Uploading Profile Images

### ISSUE THREAD

**Issue by GordiArtur** [BadgeBook/LinkedOut#21]
Move images from links to pulling directly from database

**Comment by alexanderdhsu** [comment]
According to 3 seconds of Googling, images are not typically stored in a database. So we should talk to Amir to see if that is actually what he wants or if we can store them somewhere else.

Reference: https://stackoverflow.com/questions/6472233/can-i-store-images-in-mysql

**Comment by dsim7** [comment]
We could save the images in a folder on the server and then store the path to the images in the db?

**Comment by GordiArtur** [comment]
That's the current plan

**Comment by alexanderdhsu** [comment]
After testing, we decided to store images in the database for simplicity. To allow for image storage in the user.description table, the description field was changed from VARCHAR(500) to TEXT.

**Comment by GordiArtur** [comment]
7/10
